name: Test, build, and publish

on:
  push:
    tags:
      - v*
env:
  FORCE_COLOR: 1
permissions: write-all
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Install dependencies and build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  publish_npm:
    name: Publish UI library to npm
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: sika-graph-build
          path: dist
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish @sikaeducation/ui to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
